- name: "this will be execute on master only"
  hosts: master
  become: yes
  become_method: sudo
  gather_facts: no
  tasks: 
    # - name: configure the cluster
    #   shell: |
    #     firewall-cmd --permanent --add-port=6443/tcp
    #     firewall-cmd --permanent --add-port=2379-2380/tcp
    #     firewall-cmd --permanent --add-port=10250/tcp
    #     firewall-cmd --permanent --add-port=10251/tcp
    #     firewall-cmd --permanent --add-port=10252/tcp
    #     firewall-cmd --permanent --add-port=10255/tcp
    #     firewall-cmd --permanent --add-port=8472/udp
    #     firewall-cmd --add-masquerade --permanent
    #     firewall-cmd --permanent --add-port=30000-32767/tcp
    #     systemctl restart firewalld
    #     systemctl enable kubelet.service

    # - name: Kubeadm init
    #   shell:
    #     sudo kubeadm init --pod-network-cidr=192.168.0.0/16
    #   register: init_info
    

    # - name: read the passwd file
    #     shell: cat /etc/passwd
    #   register: user_accts

    # - name: a task that only happens if the token not exists
    #   when: user_accts.stdout.find('token') != -1
    #   debug: msg="token not found"


    - name: Kubeadm list tokens
      shell:
        sudo kubeadm token list
      register: token_list
    - name: debug token_list
      debug:
        msg: "{{token_list.stdout_lines}}"
        